<a href="https://colab.research.google.com/github/AsadiAhmad/Morphology-Operators/blob/main/Code/Morphology_Operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 1: Import Libraries

In [ ]:
import numpy as np

# Step 2: Define Image with numpy

In [ ]:
image = np.array([[10, 10, 10, 20, 10, 10, 20, 10],
                  [10, 20, 20, 20, 20, 20, 20, 10],
                  [10, 10, 10, 20, 10, 20, 20, 10],
                  [10, 10, 20, 30, 10, 20, 30, 10],
                  [10, 10, 30, 10, 10, 30, 10, 20],
                  [20, 10, 30, 10, 30, 20, 20, 10],
                  [20, 20, 20, 20, 10, 10, 20, 10],
                  [20, 20, 30, 20, 20, 30, 10, 30]], dtype=np.uint8)

# Step 3: Reflect Padding

In [ ]:
def reflect_padding(image, padding_size):
    height, width = image.shape
    padded_image = np.zeros((height + padding_size*2, width + padding_size*2), dtype=image.dtype)

    padded_image[padding_size:height+padding_size, padding_size:width+padding_size] = image

    for i in range(padding_size):
        padded_image[i, padding_size:width+padding_size] = image[0, :]

    for i in range(height+padding_size, height+padding_size*2):
        padded_image[i, padding_size:width+padding_size] = image[-1, :]

    for j in range(padding_size):
        padded_image[padding_size:height+padding_size, j] = image[:, 0]

    for j in range(width+padding_size, width+padding_size*2):
        padded_image[padding_size:height+padding_size, j] = image[:, -1]

    padded_image[:padding_size, :padding_size] = image[0, 0]                    # Top-left
    padded_image[:padding_size, width+padding_size:] = image[0, -1]             # Top-right
    padded_image[height+padding_size:, :padding_size] = image[-1, 0]            # Bottom-left
    padded_image[height+padding_size:, width+padding_size:] = image[-1, -1]     # Bottom-right

    return padded_image

In [ ]:
padded_image = reflect_padding(image, 1)

In [ ]:
print(padded_image)

[[10 10 10 10 20 10 10 20 10 10]
 [10 10 10 10 20 10 10 20 10 10]
 [10 10 20 20 20 20 20 20 10 10]
 [10 10 10 10 20 10 20 20 10 10]
 [10 10 10 20 30 10 20 30 10 10]
 [10 10 10 30 10 10 30 10 20 20]
 [20 20 10 30 10 30 20 20 10 10]
 [20 20 20 20 20 10 10 20 10 10]
 [20 20 20 30 20 20 30 10 30 30]
 [20 20 20 30 20 20 30 10 30 30]]


# Step 4: Define Kernel

In [ ]:
kernel = np.array([[1, 1, 1],
                   [1, 0, 0],
                   [1, 0, 0]], dtype=np.uint8)

# Step 5: Calculate Erosion

In [ ]:
def calculate_erosion(image, kernel):
    height, width = image.shape
    kernel_height, kernel_width = kernel.shape
    kernel_height //= 2
    kernel_width //= 2

    result_image = np.zeros((height - 2*kernel_height, width - 2*kernel_width), dtype=image.dtype)
    for i in range(kernel_height, height - kernel_height):
        for j in range(kernel_width, width - kernel_width):
            matrix = image[i-kernel_height:i+kernel_height+1, j-kernel_width:j+kernel_width+1]
            multiplied = matrix * kernel
            multiplied = multiplied.flatten().tolist()
            while 0 in multiplied:
                multiplied.remove(0)
            result_image[i - kernel_height, j - kernel_width] = min(multiplied)
    return result_image

In [ ]:
erosion = calculate_erosion(padded_image, kernel)

In [ ]:
print(erosion)

[[10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 20 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [20 20 20 10 10 10 10 10]]


# Step 6: Calculate Dilation

In [ ]:
def calculate_dilation(image, kernel):
    height, width = image.shape
    kernel_height, kernel_width = kernel.shape
    kernel_height //= 2
    kernel_width //= 2

    result_image = np.zeros((height - 2*kernel_height, width - 2*kernel_width), dtype=image.dtype)
    for i in range(kernel_height, height - kernel_height):
        for j in range(kernel_width, width - kernel_width):
            matrix = image[i-kernel_height:i+kernel_height+1, j-kernel_width:j+kernel_width+1]
            multiplied = matrix * kernel
            multiplied = multiplied.flatten().tolist()
            while 0 in multiplied:
                multiplied.remove(0)
            result_image[i - kernel_height, j - kernel_width] = max(multiplied)
    return result_image

In [ ]:
dilation = calculate_dilation(padded_image, kernel)

In [ ]:
print(dilation)

[[10 10 20 20 20 20 20 20]
 [10 10 20 20 20 20 20 20]
 [20 20 20 20 30 20 20 30]
 [10 10 20 30 30 20 30 30]
 [20 20 30 30 30 30 30 30]
 [20 30 30 30 30 30 30 20]
 [20 30 30 30 30 30 30 20]
 [20 20 20 30 20 20 30 20]]
